services:
  qr-api:
    build: .
    container_name: nestro_qr
    ports:
      - "8000:8000"
    volumes:
      - ./config/qr_config.json:/app/config.json:ro

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 2s
      retries: 5

    restart: unless-stopped # после 5 перезапусков stoped
